Catalog
PavloLysiuk/TheWatchSpot pull request #31
Opened 2023-04-22 08:31 UTC by MiraDov290

2023-04-22 09:48 UTC, PavloLysiuk requested changes
need changes

2023-04-22 13:44 UTC, PavloLysiuk requested changes
Changes are needed

2023-04-24 13:49 UTC, yurchykyur approved these changes

2023-04-24 13:51 UTC, yurchykyur approved these changes

2023-04-24 13:52 UTC, PavloLysiuk approved these changes

2023-04-24 13:52 UTC, merged