Sale
PavloLysiuk/TheWatchSpot pull request #36
Opened 2023-04-22 18:25 UTC by stepanchukMax

sale review

2023-04-22 19:11 UTC, PavloLysiuk approved these changes

2023-04-23 07:10 UTC, yurchykyur requested changes
https://www.loom.com/share/3d4d140aa02141df976634881df02806
https://www.loom.com/share/e1414722e4c84bb5970d5c29300fe302
https://www.loom.com/share/3f80b93f328141428bc45bb782300a3a

2023-04-24 20:25 UTC, PavloLysiuk approved these changes

2023-04-24 20:26 UTC, yurchykyur approved these changes

2023-04-24 20:26 UTC, merged